INSERT INTO PRODUCT VALUES ('VS5', 'Vegemite Scroll');
INSERT INTO PRODUCT VALUES ('MB11', 'Blueberry Muffin');
INSERT INTO PRODUCT VALUES ('CF', 'Croissant');
COMMIT;

INSERT INTO PACK VALUES (1, 6.99, 3, 'VS5');
INSERT INTO PACK VALUES (2, 8.99, 5, 'VS5');
                               
INSERT INTO PACK VALUES (3, 9.95, 2, 'MB11');
INSERT INTO PACK VALUES (4, 16.95, 5, 'MB11');
INSERT INTO PACK VALUES (5, 24.95, 8, 'MB11');
                               
INSERT INTO PACK VALUES (6, 5.95, 3, 'CF');
INSERT INTO PACK VALUES (7, 9.95, 5, 'CF');
INSERT INTO PACK VALUES (8, 16.99, 9, 'CF');
COMMIT;